from . import library_book
from . import book_author
from . import book_publisher
from . import book_genre
from . import book_checkout
from . import book_tag
from . import res_partner
from . import book_checkout_line
from . import recommendation
from . import res_config_settings
from . import account_move
from . import account_move_line
from . import book_image
