{
    'name': 'Library Managemant',
    'version': '1.0',
    'category': 'Custom',
    'sequence': 1,
    'summary': 'Track Books ',
    'website': 'https://www.odoo.com',
    'depends': ['mail', 'account', 'base', 'website'],
    'data': [
        'data/book_sequence.xml',
        'data/book_email_template.xml',
        'data/ir_cron_data.xml',
        'security/library_management_security.xml',
        'security/ir.model.access.csv',
        'wizard/recommended_book_view.xml',
        'wizard/book_borrow_report_view.xml',
        'views/library_book_view.xml',
        'views/book_author_view.xml',
        'views/book_publisher_view.xml',
        'views/book_genre_view.xml',
        'views/book_checkout_view.xml',
        'views/book_tag_view.xml',
        'views/res_config_settings_view.xml',
        'views/res_partner_view.xml',
        'views/book_checkout_line_view.xml',
        'views/website_book_donation_template.xml',
        'views/website_book_contribution_template.xml',
        'report/book_borrow_report_template.xml',
        'report/book_borrow_report_view.xml',
        'views/website_snippet.xml',
        'views/book_image_view.xml',
        'views/library_management_menu.xml',
        'views/website_library_management_menu.xml',
    ],
    'demo': [
        'data/book_genre.xml',
        'data/book_product.xml'
    ],
    'application': True,
    'installable': True,
    'assets': {
        'web.assets_backend': [
            'library_management/static/src/js/action_manager.js',
        ],
        'web.assets_frontend': [
            'library_management/static/src/js/book_dynamic_snippet.js',
            '/library_management/static/src/xml/latest_books_snippet_template.xml',
        ],
    },
    'license': 'LGPL-3',
}
